(function(e){var f=window.AmazonUIPageJS||window.P,l=f._namespace||f.attributeErrors,d=l?l("PrimeAcquisitionMetricsJS",""):f;d.guardFatal?d.guardFatal(e)(d,window):d.execute(function(){e(d,window)})})(function(e,f,l){e.when("A","prime-page-state-helper").register("prime-forester-loggers",function(d,e,g){var c=function(a){a=a||{};var b=a.createEventData,d=a.channel,c=a.apiVersion||"1",m=a.version||"1",e=a.action||"OP";a=a.debug||!1;var h;if(b===g)throw Error("No createEventData function specified.");
if(d===g)throw Error("No channel specified.");ue!==g&&(h=ue_furl||ue.furl||g);a&&(e="TOP");this.createEventData=b;this.endpoint={protocol:"https",host:h||"fls-na.amazon.com",apiVersion:c,channel:d,version:m,action:e};this.runtime={sendMetricCount:0,logCount:0,logData:[],lastLoggedData:null,mostRecentLoggingIncomplete:!0};b=function(a,b,d){return function(c){a.resendLastData(d);try{b&&"function"===typeof b&&b(c)}catch(e){}}};f.onbeforeunload=b(this,f.onbeforeunload,"bu");f.onunload=b(this,f.onunload,
"u")},h=function(a){a=a||{};a.channel="prime-csm-metrics";a.version="1";a.pageState=a.pageState||"ms3-client-metadata";a.createEventData=function(b,c){b={id:b,ac:c,et:d.now()};this.addCSMMetadata(b);this.addMS3Metadata(b,a.pageState);return b};c.call(this,a)},k=function(a){a=a||{};a.channel="prime-presentation-metrics";a.version="1";a.pageState=a.pageState||"ms3-client-metadata";a.createEventData=function(b,c){b={id:b,pt:c,et:d.now()};this.addCSMMetadata(b);this.addMS3Metadata(b,a.pageState);return b};
c.call(this,a)};c.prototype.getEndpoint=function(){return this.endpoint.protocol+"://"+[this.endpoint.host,this.endpoint.apiVersion,this.endpoint.channel,this.endpoint.version,this.endpoint.action].join("/")};c.prototype.toJsonString=function(a){var b=f.JSON;return b&&b.stringify?b.stringify(a):"{"+d.reduce(a,function(a,b,c){b!==g&&(c='"'+c+'":',c=null===b||"[object Number]"==Object.prototype.toString.call(b)?c+b:c+('"'+b+'"'),a.push(c));return a},[]).join(",")+"}"};c.prototype.addMetric=function(a){this.runtime.logCount+=
1;a=this.createEventData(this.runtime.logCount,a);this.runtime.logData.push(a);this.runtime.lastLoggedData=a;d.delay(function(a){return function(){a.sendMetric()}}(this))};c.prototype.sendMetric=function(){for(var a=function(a,b){return function(){a.runtime.logData.push(b);a.runtime.mostRecentLoggingIncomplete=!0}};0<this.runtime.logData.length;){this.runtime.sendMetricCount+=1;var b=new Image,c=this.runtime.logData.shift();b.src=this.getEndpoint()+"/"+this.toJsonString(c)+this.runtime.sendMetricCount;
b.onabort=a(this,c)}};c.prototype.resendLastData=function(a){if(null!==this.runtime.lastLoggedData&&this.runtime.mostRecentLoggingIncomplete){var b=d.copy(this.runtime.lastLoggedData);b.le=a;this.runtime.logData.push(b);this.runtime.mostRecentLoggingIncomplete=!1;this.sendMetric()}};c.prototype.addCSMMetadata=function(a){if(ue!==g){if(ue_sid||ue.sid)a.s=ue_sid||ue.sid;ue.rid&&(a.r=ue.rid)}};c.prototype.addMS3Metadata=function(a,b){b=e.get(b);b!==g&&(b.containerRequestID&&(a.mgid=b.containerRequestID),
b.customerID&&(a.cid=b.customerID),b.marketplaceID&&(a.mkt=b.marketplaceID))};Object&&Object.create?(h.prototype=Object.create(c.prototype),k.prototype=Object.create(c.prototype)):(h.prototype=d.copy(c.prototype),h.prototype.constructor=h,k.prototype=d.copy(c.prototype),k.prototype.constructor=k);return{BaseLogger:c,EventLogger:h,PresentationLogger:k}});e.when("A").register("prime-page-state-helper",function(d){return{get:function(e){var g={};d.each(d.$('script[type\x3d"a-state"]'),function(c,f){d.$(c).data("a-state").key===
e&&(g=d.parseJSON(d.$(c).html()))});return g}}})});
/* ******** */
(function(b){var c=window.AmazonUIPageJS||window.P,e=c._namespace||c.attributeErrors,a=e?e("PrimeCheckoutAssets",""):c;a.guardFatal?a.guardFatal(b)(a,window):a.execute(function(){b(a,window)})})(function(b,c,e){b.when("A","ready").register(function(a){a.$("#checkoutDisplayPage").bind("DOMSubtreeModified",function(){a.$("#foldableMembershipLegalStatementSeeMoreButton").click(function(){a.$("#foldableMembershipLegalStatementPartial").addClass("aok-hidden");a.$("#foldableMembershipLegalStatementFull").removeClass("aok-hidden");
a.$("#foldableMembershipLegalStatementSeeMoreButton").addClass("aok-hidden")})})});b.when("A","prime-forester-loggers","prime-page-state-helper","page-detector").register("prime-events",function(a,b,e,m){function g(){if(!h){var a=e.get("ms3-client-metadata");a&&(d=new b.EventLogger({marketplace:a.marketplaceID}),h=!0)}}var d,h=!1;m.isSpc()&&g();a.on("checkout:reload:spc",function(a){g()});a.declarative("prime-event","click",function(a){d&&d.addMetric(a.data.metric)});a.$(document).delegate("[data-prime-metric]",
"click touchend",function(f){(f=a.$(this).data("prime-metric"))&&d.addMetric(f)});a.on("a:popover:dismiss:prime-acquisition-spc-popover",function(a){d&&d.addMetric("ac1")});a.on("a:popover:show:prime-acquisition-spc-popover",function(a){0===a.popover.$popover.find("form").length&&c.ue&&c.ue.tag&&c.uex&&(c.ue.tag("prime-spc-popover-fallback-hit"),c.uex("ld","primePopoverFallback"))});return{getLogger:function(){return d}}});b.when("A","prime-forester-loggers","prime-page-state-helper","page-detector").register("prime-presentations",
function(a,c,b,e){function g(a){var b=h[a];if(b)return b;b=new c.PresentationLogger({pageState:a});return h[a]=b}function d(a){return function(){var c,d;if(c=b.get(a))d=g(a),d.addMetric(c.pageType)}}var h={},f={SPC:"ms3-client-metadata",PCI:"ms3-client-metadata-pci"},k=d(f.SPC),l=d(f.PCI);e.isSpc()&&k();0<a.$("div#prime.spp-panel.expanded").length&&l();a.on("checkout:reload:spc",k);a.on("checkout:reload:spp-prime",l);return{metadataKeys:f,getLogger:function(){return g(f.SPC)},getLoggerForPage:g,clearCache:function(){h=
{}}}})});
/* ******** */
